### PR TITLE
CT-1170: Add Income Check

### PR DESCRIPTION
**Pull request by filiplindqvist-tink**

### CODE REVIEW

**Review by alexandrezagame — DISMISSED** [review]

**Comment by filiplindqvist-tink** [comment]
Wait, description needs to be updated.

**Comment by filiplindqvist-tink** [comment]
@npivic Can you QA test this?

**Comment by filiplindqvist-tink** [comment]
@npivic

**Comment by npivic** [comment]
@filiplindqvist-tink Thanks! @Tink-ScottJacobs will test both this collection and the one for Risk Insights. When done, we'll get back.

**Comment by npivic** [comment]
@filiplindqvist-tink I've heard both collections work perfectly, there's just little thing that I feel should be changed: in the Variables list, can you please switch places for `report_id` and `access_token`? This goes both for the Postman collection for Income Check and Risk Insights.

The change would keep the variables in the order in which they are received.

After that change, I'll happily publish them!

**Comment by filiplindqvist-tink** [comment]
@npivic Fixed

**Review by npivic — APPROVED** [review]

**Pull request merged**
