### PR TITLE
[ACCT-355]: fix(Investments): Refactored Assets and Liabilities

### PR DESCRIPTION
**Pull request by zmurfen**
Changed names from Assets and Liabilities to Investments and Loans.
Fixed scopes for Loans to only contain necessary scopes.

### CODE REVIEW

**Review by jangillich — COMMENTED** [review]
Looks good in general 👍 
Should the `.idea` folder be ignored or was that committed on purpose?

**Comment by zmurfen** [comment]
> Looks good in general 👍 Should the `.idea` folder be ignored or was that committed on purpose?

It should be ignored, will fix it

**Review by jangillich — APPROVED** [review]
🙌

**Comment by zmurfen** [comment]
@jangillich feel free to merge this when you get time for it. I don't have write access to this repository so i can't merge it

**Pull request merged**
